### ISSUE TITLE
Taking action in env

### ISSUE THREAD

**Issue by chaubeyniha** [Kinds-of-Intelligence-CFI/animal-ai#2]
In the AnimalAI environment, when you want to take a step, the action has to be called as action.item(). This may be an issue with AnimalAI or it could be due to the way stable baselines stores the model.

while not done:
     action, _states = model.predict(obs)
     obs, rewards, done, info = env.step(action.item())
     env.render()

**Comment by alhasacademy96** [comment]
For anyone having the same issue in their python scripts, a quick fix to this, per Niha, would be (depending on which Gym you use, as this is valid for OpenAI at least):

Where you specify the condition on when and if your agent should learn, simply access the env.step() method by specifying the action.item() method within it. This method accepts an action and returns a tuple ("[ObsType, float, bool, bool, dict]"). 

```

while not done:
action, _states = model.predict(obs)
obs, rewards, done, info = env.step(action.item()) #Here, change: env.step(action) to: env.step(action,item). 
env.render()

```

According to the documentation on OpenAI's GitHub: https://github.com/openai/gym/blob/master/gym/core.py, lines 382 to 385. 
It is likely that the wrapper needs further implementation when using AAI, hence calling "env.step(aaction.item)".
