### ISSUE TITLE
Environment download needs to be renamed.

### ISSUE THREAD

**Issue by gramcracker** [Kinds-of-Intelligence-CFI/animal-ai#20]
It took me a bit to figure this out, but (at least for the linux version) you have to rename the environment executable and environment data folder to "AnimalAI.x86_64", and "AnimalAI_Data" in order for play.py to recognize it. Additionaly, when you extract the folder, you still have to move the files inside the sub-directory to its parent folder. The instructions fail to mention this, making it difficult to run an example.

**Comment by alhasacademy96** [comment]
Thanks, and apologies gramcracker. Are you now able to use our platform without any issues as you highlighted? Is it just the name changes and making sure the files are in the sub-directory to its parent folder that need to be investigated? 

-Ibrahim, Lead Software Engineer @ AAI.

**Comment by alhasacademy96** [comment]
Furthermore, please be aware that this issue has been partly mentioned in the Release Section of the repo, specifically in the details panel: "N.B: If you are using Linux, you may need to make the .exe file executable: Simply run this command in your terminal: chmod +x env/AnimalAI.x86_64. If you are using MacOS, you may also need to run this command: chmod -R 777 [applicationName].app in your MacOS terminal to unlock permissions for running the application." --> https://github.com/Kinds-of-Intelligence-CFI/animal-ai/releases/tag/v3.0.2.

**Comment by gramcracker** [comment]
Yes, thank you. You are very fast!

**Comment by alhasacademy96** [comment]
I will now close the issue. Please submit a new issue if the error persists :)
