### ISSUE TITLE
Getting the environment for Mac

### ISSUE THREAD

**Issue by eleninisioti** [Kinds-of-Intelligence-CFI/animal-ai#30]
I was wondering whether there is something wrong with the environment zip for Mac. When I try to download  it the link does not work. When I navigate to the website the link points to and download it, I get an app file that my Mac cannot open nor unzip (running Ventura 13.0).

**Comment by alhasacademy96** [comment]
Hi @eleninisioti, have you made sure to follow the exact installation process, also the notes section?: 

"If you are using MacOS, you may also need to run this command: chmod -R 777 [applicationName].app in your MacOS terminal to unlock permissions for running the application. Edit: Please also make sure when you extract the folder, you move the files inside the sub-directory to its parent folder."

I've downloaded the macOS version of AAI just now and everything is fine. Could you elaborate more on the issue?

-Ibrahim
Lead Software Engineer

**Comment by alhasacademy96** [comment]
Im going to assume that the issue is now solved. If not, please post an issue again.
