### ISSUE TITLE
Remove .egg from version control.

### ISSUE THREAD

**Issue by wschella** [Kinds-of-Intelligence-CFI/animal-ai#31]
As far as I know, this should not be committed to version control. It might also be interfering with normal collection of sources. As far as I know, we don't do anything special, and everything should be possible to specify in setup.py.

**Comment by alhasacademy96** [comment]
@kozzy97 has this been resolved?

**Comment by kozzy97** [comment]
Not yet, I can do it now.

**Comment by kozzy97** [comment]
I've removed the egg and added a gitignore for future builds in this commit 28faa8529d8ef255acd3ab3b262e85e60264abe8.

Maybe we need to consider moving to a .toml or a .whl to build some of the scripts? Relatedly, I have access to the PyPI package now, so we should update that too.
