### ISSUE TITLE
Failing to run examples/gymwrapper.py

### ISSUE THREAD

**Issue by eleninisioti** [Kinds-of-Intelligence-CFI/animal-ai#35]
I would like to test whether I can use the environment as a gym enviromnent with an RL agent. I am running it on a server and would like the environment to have no graphics. For this I am running the script examples/gymwrapper.py , having added no_graphics=True when calling AnimalAIEnvironment(). However I must be doing something wrong because the script gets stuck and then times out with message:

`[UnityMemory] Configuration Parameters - Can be set up in boot.config
    "memorysetup-bucket-allocator-granularity=16"
    "memorysetup-bucket-allocator-bucket-count=8"
    "memorysetup-bucket-allocator-block-size=4194304"
    "memorysetup-bucket-allocator-block-count=1"
    "memorysetup-main-allocator-block-size=16777216"
    "memorysetup-thread-allocator-block-size=16777216"
    "memorysetup-gfx-main-allocator-block-size=16777216"
    "memorysetup-gfx-thread-allocator-block-size=16777216"
    "memorysetup-cache-allocator-block-size=4194304"
    "memorysetup-typetree-allocator-block-size=2097152"
    "memorysetup-profiler-bucket-allocator-granularity=16"
    "memorysetup-profiler-bucket-allocator-bucket-count=8"
    "memorysetup-profiler-bucket-allocator-block-size=4194304"
    "memorysetup-profiler-bucket-allocator-block-count=1"
    "memorysetup-profiler-allocator-block-size=16777216"
    "memorysetup-profiler-editor-allocator-block-size=1048576"
    "memorysetup-temp-allocator-size-main=4194304"
    "memorysetup-job-temp-allocator-block-size=2097152"
    "memorysetup-job-temp-allocator-block-size-background=1048576"
    "memorysetup-job-temp-allocator-reduction-small-platforms=262144"
    "memorysetup-temp-allocator-size-background-worker=32768"
    "memorysetup-temp-allocator-size-job-worker=262144"
    "memorysetup-temp-allocator-size-preload-manager=262144"
    "memorysetup-temp-allocator-size-nav-mesh-worker=65536"
    "memorysetup-temp-allocator-size-audio-worker=65536"
    "memorysetup-temp-allocator-size-cloud-worker=32768"
    "memorysetup-temp-allocator-size-gfx=262144"
INFO:mlagents_envs:Environment timed out shutting down. Killing...
Traceback (most recent call last):
  File "/home/eleni/eleni/workspace/playground/GrowAIenvs/animal-ai/animalai/../examples/gymwrapper.py", line 62, in <module>
    train_agent_single_config(configuration_file=configuration_file)
  File "/home/eleni/eleni/workspace/playground/GrowAIenvs/animal-ai/animalai/../examples/gymwrapper.py", line 15, in train_agent_single_config
    aai_env = AnimalAIEnvironment(
  File "/home/eleni/eleni/workspace/playground/GrowAIenvs/animal-ai/animalai/./animalai/envs/environment.py", line 145, in __init__
    super().__init__(
  File "/home/eleni/anaconda3/envs/animalAIp10/lib/python3.10/site-packages/mlagents_envs/environment.py", line 142, in __init__
    aca_output = self.send_academy_parameters(rl_init_parameters_in)
  File "/home/eleni/anaconda3/envs/animalAIp10/lib/python3.10/site-packages/mlagents_envs/environment.py", line 549, in send_academy_parameters
    return self.communicator.initialize(inputs)
  File "/home/eleni/anaconda3/envs/animalAIp10/lib/python3.10/site-packages/mlagents_envs/rpc_communicator.py", line 98, in initialize
    self.poll_for_timeout()
  File "/home/eleni/anaconda3/envs/animalAIp10/lib/python3.10/site-packages/mlagents_envs/rpc_communicator.py", line 90, in poll_for_timeout
    raise UnityTimeOutException(
mlagents_envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
	 The environment does not need user interaction to launch
	 The Agents are linked to the appropriate Brains
	 The environment and the Python interface have compatible versions.`

**Comment by alhasacademy96** [comment]
Hi @eleninisioti, could you provide the following details?: 

OS
Version of AAI you are using
Python Version you are using
+ any other relevant information such as the steps you take that result in these error(s).

**Comment by eleninisioti** [comment]
I have created this notebook to reproduce the problem. If we manage to run this notebook correctly, I should be able to run it locally as well : https://colab.research.google.com/drive/10tsWS7JPjKiSnoRoXLSKF0drYBZiBYWS?usp=sharing

To respond to your question about my local installation:

My OS is Ventura 13.0 on an Apple M2 Pro, running python 3.10.0
I am installing animalai with pip and getting version 2.0.0

**Comment by alhasacademy96** [comment]
Could you confirm that you are actually using AAI2, which is actually depreciated? Are you aware that this GitHub is for AAI-Version 3? @eleninisioti

**Comment by eleninisioti** [comment]
Yep indeed, I was installing version 2 with pip. I removed this line in my notebook. Now I am wondering what is the proper way to install dependences. For example there is an issue with gym-unity. I have version 0.15.0 installed which gives the error `cannot import name 'UnityToGymWrapper' from 'gym_unity.envs' (/usr/local/lib/python3.10/dist-packages/gym_unity/envs/__init__.py)` so AAI3 must be requiring a different version.

**Comment by issamansur** [comment]
Good night! Please, reinstall this requirement:
(you use 0.15.0, but gym_unity.envs contains UnityToGymWrapper from 1.16.0)
```
!pip install gym-unity==0.16.0
```
and restart enviroment to save changes

**Comment by eleninisioti** [comment]
Thanks, i got gym-unity 0.16.0 but I am still getting the same error (UnityTImeoutExpection in the first comment).
Also note that I had to comment out the additional_args and log_folder argument in the environment.py file because calling `UnityEnvironment.__init__()` was throwing an error. I suspect there is still a package mismatch, probaly with mlagents-envs, which is 0.16.0 on the notebook

**Comment by issamansur** [comment]
1. Maybe it correctly visual observations are only supported when a (game-)window is rendered.
By using "no_graphics = true" you are explicitly telling unity NOT to render a game-window.
Can you try with "no_graphics=false" and see if that fixes your issue?
2. Also u can use xvfb with ml-agents. See this [post](https://forum.unity.com/threads/how-do-i-get-visual-observations-in-headless-environment.927530/) and [issue](https://github.com/Unity-Technologies/ml-agents/issues/1786#issuecomment-551280552)

**Comment by alhasacademy96** [comment]
Hi @eleninisioti, as AAIV2 is no longer supported and depreciated, it's hard to pinpoint the error as it's been a while since anyone has actually used it. Please do use AAIV3 as this is a much improved AAI, with ongoing active support and development.

**Comment by alhasacademy96** [comment]
Hi @eleninisioti, has the problem you're encountering been fixed?

**Comment by alhasacademy96** [comment]
I will assume the problem has now been fixed and that no further discussion is required. If not, please open a new issue post.
