### ISSUE TITLE
Incompatible with RLLib

### ISSUE THREAD

**Issue by chaubeyniha** [Kinds-of-Intelligence-CFI/animal-ai#4]
The Animal AI environment is incompatible with RLLib because the gym wrapper that is used is a tuple whereas RL Lib needs it to be an object.

**Comment by alhasacademy96** [comment]
Hi @chaubeyniha 

Could you please elaborate on the issue? What is the error message produced? Where is the error produced? What platform are you on that the error keeps popping up or when does it pop up?
