### ISSUE TITLE
Close and Restart AAI for multiple yaml files

### ISSUE THREAD

**Issue by chaubeyniha** [Kinds-of-Intelligence-CFI/animal-ai#5]
The following error arises if you want one script to sequentially test agents on various yaml files. 

mlagents_envs.exception.UnityWorkerInUseException: Couldn't start socket communication because worker number 0 is still in use. You may need to manually close a previously opened environment or use a different worker number.

**Comment by alhasacademy96** [comment]
As we discussed, a simple method would be to implement a method that assigns a random value to the socket port, which should be specified by you before running the application. This would allow for infinite sequential agents to run without having to use the same port number. 

E.g. 
Socket_port = 5000 + random.randint(x, y), where x and y are the intervals for the random int initializer.
