### ISSUE TITLE
Q: Do you provide baseline algorithm mentioned in the paper?

### ISSUE THREAD

**Issue by ugurbolat** [Kinds-of-Intelligence-CFI/animal-ai#52]
Hi,

Do you provide baseline algorithms somewhere mentioned in the paper in a reproducible manner? I couldn't find it in the animal-ai-python repo as well. This is especially crucial for RL's hyperparameters.

Best,
Ugur

**Comment by alhasacademy96** [comment]
Merhabalar Uğur bey,

Please speak to the team responsible for experimentation in our paper directly via email. They will be happy to help: 

Konstantinos Voudouris <kv301@cam.ac.uk>

Wout Schellaert <wschell@vrain.upv.es>

Best,

Ibrahim Alhas
Lead Software Engineer
