### ISSUE TITLE
Configurable Camera Positions and Use of 'n' button for human play via YAML

### ISSUE THREAD

**Issue by kozzy97** [Kinds-of-Intelligence-CFI/animal-ai#7]
In the Python API in "player mode", it would be great to have an option to call the `AAIEnvironment` class with certain features disabled. At the moment, you can press /c/ to change the camera view, and press /n/ and/or /r/ to reset or skip to the next episode. When using this for human testing, we would like to be able to disable these features, selecting only one camera view, and disabling the skips. At the moment, we are getting round this by using a different build with those features disabled inside the C# scripts, but if we could do this through the API that would be great.

**Comment by alhasacademy96** [comment]
Hey @kozzy97, I couldn't find any code that defines which perspective the camera is launched with during Play on python side of things. I believe this is written in code in unity side. Have I missed something? Can you show me where in the API where this is defined (python side)?

**Comment by kozzy97** [comment]
Hi @alhasacademy96, there isn't anything yet. Currently, the AnimalAIEnvironment is called using this [class](https://github.com/Kinds-of-Intelligence-CFI/animal-ai/blob/main/animalai/animalai/envs/environment.py). I propose the following:

```
class AnimalAIEnvironment(UnityEnvironment):
    ...
    def __init__(
        self,
        ...
        inference: bool = False #already exists
        play: bool = False, #already exists
        ...
        camera: str = "first-person" #with other options for "birds-eye" and "third-person", for example
        skip-enable: bool = True #can participants in play mode skip episodes by pressing 'n' or 'r'?
        ):
```

These bools would control behaviour in this [file](https://github.com/Kinds-of-Intelligence-CFI/animal-ai-unity-project/blob/main/Assets/Scripts/PlayerControls.cs) (lines 46-67 plus anything downstream of that).

I think these updates should be built with a view to eventually allowing agents to be trained on different camera views. But for now, the priority is to provide options for play mode (so `camera` and `skip-enable` would be ignored when `play = False`.

**Comment by alhasacademy96** [comment]
I’ve already modified the script to always accept a Boolean (set true for both by default) whether the episode can be skipped or camera perspectives can be changed :) see branch end of episode notification which includes all my current commits :)

This makes it flexible as the user can choose which to turn on/off individually. This should be a good starting point.
